version: '2.1'

services:
  database-postgres:
    container_name: postgres-db_new
    image: postgres:11.2
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data_new:/var/lib/postgresql/data
volumes:
  postgres-data_new: